### ISSUE TITLE
Testing the plugin

### ISSUE THREAD

**Issue by paaljoachim** [soderlind/super-admin-all-sites-menu#2]
Hei Per!

Jeg driver og prøver ut din plugin (I am testing your plugin) as I noticed you posted about it here:
https://core.trac.wordpress.org/ticket/15317

Before:
![Screen Shot 2021-08-17 at 13 58 02](https://user-images.githubusercontent.com/5323259/129721711-be4d2d81-bc73-47ee-b9b6-2a1e3ec86d09.jpg)

After - activating Super Admin All Sites Menu:
![Screen Shot 2021-08-17 at 13 58 25](https://user-images.githubusercontent.com/5323259/129721752-2af59ae2-7ce9-40ad-b68d-82c36fea24f8.jpg)

There is a long grey area seen.

Btw
I have another mockup suggestion.
![Search-sites](https://user-images.githubusercontent.com/5323259/129725215-ca71f275-09cf-450d-a5eb-c0023f13e97c.jpg)

**Comment by soderlind** [comment]
![all-sites](https://user-images.githubusercontent.com/1649452/130518389-8b9bdc28-6fc5-4eaa-9e9b-1763e9d43c48.gif)

**Comment by paaljoachim** [comment]
Hei Per

Comparing with the existing All Sites drop down.
![Screen Shot 2021-08-23 at 23 03 51](https://user-images.githubusercontent.com/5323259/130519186-ed8f6ae6-544e-4219-a822-5f25530d401a.jpg)

Your plugin offers a search area, and additional links one can enter.
All in all a nice improvement!
